version: '3.9'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm start api-gateway
    ports:
      - '8081:8080'
    environment:
      - NODE_ENV=production
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm start auth
    ports:
      - '50001:50001'
    environment:
      - NODE_ENV=production
